require 'C:/Users/julio/pix/myousoftware.com/applets/cross-platform/main'
require 'C:/Users/julio/pix/myousoftware.com/applets/designed_for_web/main'
require 'C:/Users/julio/pix/myousoftware.com/applets/easy/main'
require 'C:/Users/julio/pix/myousoftware.com/applets/open-source/main'
require 'C:/Users/julio/pix/myousoftware.com/applets/powerful/main'
require 'C:/Users/julio/pix/myousoftware.com/applets/rotating_cube/main'
require 'C:/Users/julio/pix/myousoftware.com/applets/vr/main'
